name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-macos:
    strategy:
      matrix:
        xcode-version: ['16.1_beta'] # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    runs-on: macos-latest
    timeout-minutes: 3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - uses: actions/checkout@v4
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test
  test-on-linux:
    strategy:
      matrix:
        swift-version: ['6.0-snapshot']
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift ${{ matrix.swift-version }}
        run: |
          curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y
          swiftly install ${{ matrix.swift-version }}
      - name: Run swift --version
        run: swift --version
      - name: Run swift build
        run: swift build
      - name: Run swift test
        run: swift test
